-- -----------------------------------------------------
-- Table estado
-- -----------------------------------------------------
INSERT INTO estado (codigo, sigla, nome) VALUES (01, 'AC', 'Acre');
INSERT INTO estado (codigo, sigla, nome) VALUES (02, 'AL', 'Alagoas');
INSERT INTO estado (codigo, sigla, nome) VALUES (03, 'AP', 'Amapá');
INSERT INTO estado (codigo, sigla, nome) VALUES (04, 'AM', 'Amazonas');
INSERT INTO estado (codigo, sigla, nome) VALUES (05, 'BA', 'Bahia');
INSERT INTO estado (codigo, sigla, nome) VALUES (06, 'CE', 'Ceará');
INSERT INTO estado (codigo, sigla, nome) VALUES (07, 'DF', 'Distrito Federal');
INSERT INTO estado (codigo, sigla, nome) VALUES (08, 'ES', 'Espírito Santo');
INSERT INTO estado (codigo, sigla, nome) VALUES (09, 'GO', 'Goiás');
INSERT INTO estado (codigo, sigla, nome) VALUES (10, 'MA', 'Maranhão');
INSERT INTO estado (codigo, sigla, nome) VALUES (11, 'MT', 'Mato Grosso');
INSERT INTO estado (codigo, sigla, nome) VALUES (12, 'MS', 'Mato Grosso do Sul');
INSERT INTO estado (codigo, sigla, nome) VALUES (13, 'MG', 'Minas Gerais');
INSERT INTO estado (codigo, sigla, nome) VALUES (14, 'PA', 'Pará');
INSERT INTO estado (codigo, sigla, nome) VALUES (15, 'PB', 'Paraíba');
INSERT INTO estado (codigo, sigla, nome) VALUES (16, 'PR', 'Paraná');
INSERT INTO estado (codigo, sigla, nome) VALUES (17, 'PE', 'Pernambuco');
INSERT INTO estado (codigo, sigla, nome) VALUES (18, 'PI', 'Piauí');
INSERT INTO estado (codigo, sigla, nome) VALUES (19, 'RJ', 'Rio de Janeiro');
INSERT INTO estado (codigo, sigla, nome) VALUES (20, 'RN', 'Rio Grande do Norte');
INSERT INTO estado (codigo, sigla, nome) VALUES (21, 'RS', 'Rio Grande do Sul');
INSERT INTO estado (codigo, sigla, nome) VALUES (22, 'RO', 'Rondônia');
INSERT INTO estado (codigo, sigla, nome) VALUES (23, 'RR', 'Roraima');
INSERT INTO estado (codigo, sigla, nome) VALUES (24, 'SC', 'Santa Catarina');
INSERT INTO estado (codigo, sigla, nome) VALUES (25, 'SP', 'São Paulo');
INSERT INTO estado (codigo, sigla, nome) VALUES (26, 'SE', 'Sergipe');
INSERT INTO estado (codigo, sigla, nome) VALUES (27, 'TO', 'Tocantins');

-- -----------------------------------------------------
-- Table cidade
-- -----------------------------------------------------
-- Rio Grande do Sul
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3822, 21, 'Água Santa');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3823, 21, 'Agudo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3824, 21, 'Ajuricaba');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3825, 21, 'Alecrim');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3826, 21, 'Alegrete');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3827, 21, 'Alegria');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3828, 21, 'Alpestre');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3829, 21, 'Alto Alegre');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3830, 21, 'Alto Feliz');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3831, 21, 'Alvorada');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3832, 21, 'Amaral Ferrador');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3833, 21, 'Ametista do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3834, 21, 'André da Rocha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3835, 21, 'Anta Gorda');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3836, 21, 'Antônio Prado');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3837, 21, 'Arambaré');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3838, 21, 'Araricá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3839, 21, 'Aratiba');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3840, 21, 'Arroio do Meio');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3841, 21, 'Arroio do Sal');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3842, 21, 'Arroio do Tigre');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3843, 21, 'Arroio dos Ratos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3844, 21, 'Arroio Grande');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3845, 21, 'Arvorezinha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3846, 21, 'Augusto Pestana');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3847, 21, 'Áurea');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3848, 21, 'Bagé');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3849, 21, 'Balneário Pinhal');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3850, 21, 'Barão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3851, 21, 'Barão de Cotegipe');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3852, 21, 'Barão do Triunfo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3853, 21, 'Barra do Guarita');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3854, 21, 'Barra do Quaraí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3855, 21, 'Barra do Ribeiro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3856, 21, 'Barra do Rio Azul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3857, 21, 'Barra Funda');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3858, 21, 'Barracão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3859, 21, 'Barros Cassal');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3860, 21, 'Benjamin Constant do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3861, 21, 'Bento Gonçalves');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3862, 21, 'Boa Vista das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3863, 21, 'Boa Vista do Buricá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3864, 21, 'Boa Vista do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3865, 21, 'Bom Jesus');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3866, 21, 'Bom Princípio');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3867, 21, 'Bom Progresso');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3868, 21, 'Bom Retiro do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3869, 21, 'Boqueirão do Leão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3870, 21, 'Bossoroca');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3871, 21, 'Braga');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3872, 21, 'Brochier');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3873, 21, 'Butiá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3874, 21, 'Caçapava do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3875, 21, 'Cacequi');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3876, 21, 'Cachoeira do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3877, 21, 'Cachoeirinha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3878, 21, 'Cacique Doble');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3879, 21, 'Caibaté');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3880, 21, 'Caiçara');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3881, 21, 'Camaquã');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3882, 21, 'Camargo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3883, 21, 'Cambará do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3884, 21, 'Campestre da Serra');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3885, 21, 'Campina das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3886, 21, 'Campinas do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3887, 21, 'Campo Bom');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3888, 21, 'Campo Novo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3889, 21, 'Campos Borges');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3890, 21, 'Candelária');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3891, 21, 'Cândido Godói');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3892, 21, 'Candiota');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3893, 21, 'Canela');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3894, 21, 'Canguçu');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3895, 21, 'Canoas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3896, 21, 'Capão da Canoa');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3897, 21, 'Capão do Leão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3898, 21, 'Capela de Santana');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3899, 21, 'Capitão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3900, 21, 'Capivari do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3901, 21, 'Caraá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3902, 21, 'Carazinho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3903, 21, 'Carlos Barbosa');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3904, 21, 'Carlos Gomes');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3905, 21, 'Casca');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3906, 21, 'Caseiros');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3907, 21, 'Catuípe');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3908, 21, 'Caxias do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3909, 21, 'Centenário');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3910, 21, 'Cerrito');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3911, 21, 'Cerro Branco');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3912, 21, 'Cerro Grande');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3913, 21, 'Cerro Grande do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3914, 21, 'Cerro Largo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3915, 21, 'Chapada');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3916, 21, 'Charqueadas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3917, 21, 'Charrua');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3918, 21, 'Chiapeta');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3919, 21, 'Chuí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3920, 21, 'Chuvisca');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3921, 21, 'Cidreira');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3922, 21, 'Ciríaco');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3923, 21, 'Colinas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3924, 21, 'Colorado');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3925, 21, 'Condor');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3926, 21, 'Constantina');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3927, 21, 'Coqueiros do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3928, 21, 'Coronel Barros');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3929, 21, 'Coronel Bicaco');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3930, 21, 'Cotiporã');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3931, 21, 'Coxilha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3932, 21, 'Crissiumal');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3933, 21, 'Cristal');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3934, 21, 'Cristal do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3935, 21, 'Cruz Alta');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3936, 21, 'Cruzeiro do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3937, 21, 'David Canabarro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3938, 21, 'Derrubadas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3939, 21, 'Dezesseis de Novembro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3940, 21, 'Dilermando de Aguiar');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3941, 21, 'Dois Irmãos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3942, 21, 'Dois Irmãos das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3943, 21, 'Dois Lajeados');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3944, 21, 'Dom Feliciano');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3945, 21, 'Dom Pedrito');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3946, 21, 'Dom Pedro de Alcântara');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3947, 21, 'Dona Francisca');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3948, 21, 'Doutor Maurício Cardoso');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3949, 21, 'Doutor Ricardo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3950, 21, 'Eldorado do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3951, 21, 'Encantado');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3952, 21, 'Encruzilhada do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3953, 21, 'Engenho Velho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3954, 21, 'Entre Rios do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3955, 21, 'Entre-Ijuís');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3956, 21, 'Erebango');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3957, 21, 'Erechim');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3958, 21, 'Ernestina');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3959, 21, 'Erval Grande');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3960, 21, 'Erval Seco');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3961, 21, 'Esmeralda');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3962, 21, 'Esperança do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3963, 21, 'Espumoso');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3964, 21, 'Estação');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3965, 21, 'Estância Velha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3966, 21, 'Esteio');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3967, 21, 'Estrela');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3968, 21, 'Estrela Velha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3969, 21, 'Eugênio de Castro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3970, 21, 'Fagundes Varela');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3971, 21, 'Farroupilha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3972, 21, 'Faxinal do Soturno');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3973, 21, 'Faxinalzinho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3974, 21, 'Fazenda Vilanova');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3975, 21, 'Feliz');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3976, 21, 'Flores da Cunha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3977, 21, 'Floriano Peixoto');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3978, 21, 'Fontoura Xavier');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3979, 21, 'Formigueiro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3980, 21, 'Fortaleza dos Valos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3981, 21, 'Frederico Westphalen');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3982, 21, 'Garibaldi');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3983, 21, 'Garruchos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3984, 21, 'Gaurama');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3985, 21, 'General Câmara');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3986, 21, 'Gentil');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3987, 21, 'Getúlio Vargas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3988, 21, 'Giruá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3989, 21, 'Glorinha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3990, 21, 'Gramado');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3991, 21, 'Gramado dos Loureiros');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3992, 21, 'Gramado Xavier');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3993, 21, 'Gravataí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3994, 21, 'Guabiju');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3995, 21, 'Guaíba');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3996, 21, 'Guaporé');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3997, 21, 'Guarani das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3998, 21, 'Harmonia');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (3999, 21, 'Herval');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4000, 21, 'Herveiras');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4001, 21, 'Horizontina');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4002, 21, 'Hulha Negra');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4003, 21, 'Humaitá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4004, 21, 'Ibarama');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4005, 21, 'Ibiaçá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4006, 21, 'Ibiraiaras');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4007, 21, 'Ibirapuitã');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4008, 21, 'Ibirubá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4009, 21, 'Igrejinha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4010, 21, 'Ijuí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4011, 21, 'Ilópolis');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4012, 21, 'Imbé');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4013, 21, 'Imigrante');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4014, 21, 'Independência');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4015, 21, 'Inhacorá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4016, 21, 'Ipê');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4017, 21, 'Ipiranga do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4018, 21, 'Iraí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4019, 21, 'Itaara');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4020, 21, 'Itacurubi');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4021, 21, 'Itapuca');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4022, 21, 'Itaqui');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4023, 21, 'Itatiba do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4024, 21, 'Ivorá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4025, 21, 'Ivoti');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4026, 21, 'Jaboticaba');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4027, 21, 'Jacutinga');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4028, 21, 'Jaguarão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4029, 21, 'Jaguari');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4030, 21, 'Jaquirana');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4031, 21, 'Jari');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4032, 21, 'Jóia');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4033, 21, 'Júlio de Castilhos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4034, 21, 'Lagoa dos Três Cantos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4035, 21, 'Lagoa Vermelha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4036, 21, 'Lagoão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4037, 21, 'Lajeado');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4038, 21, 'Lajeado do Bugre');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4039, 21, 'Lavras do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4040, 21, 'Liberato Salzano');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4041, 21, 'Lindolfo Collor');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4042, 21, 'Linha Nova');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4043, 21, 'Maçambara');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4044, 21, 'Machadinho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4045, 21, 'Mampituba');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4046, 21, 'Manoel Viana');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4047, 21, 'Maquiné');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4048, 21, 'Maratá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4049, 21, 'Marau');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4050, 21, 'Marcelino Ramos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4051, 21, 'Mariana Pimentel');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4052, 21, 'Mariano Moro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4053, 21, 'Marques de Souza');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4054, 21, 'Mata');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4055, 21, 'Mato Castelhano');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4056, 21, 'Mato Leitão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4057, 21, 'Maximiliano de Almeida');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4058, 21, 'Minas do Leão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4059, 21, 'Miraguaí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4060, 21, 'Montauri');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4061, 21, 'Monte Alegre dos Campos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4062, 21, 'Monte Belo do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4063, 21, 'Montenegro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4064, 21, 'Mormaço');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4065, 21, 'Morrinhos do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4066, 21, 'Morro Redondo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4067, 21, 'Morro Reuter');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4068, 21, 'Mostardas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4069, 21, 'Muçum');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4070, 21, 'Muitos Capões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4071, 21, 'Muliterno');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4072, 21, 'Não-Me-Toque');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4073, 21, 'Nicolau Vergueiro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4074, 21, 'Nonoai');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4075, 21, 'Nova Alvorada');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4076, 21, 'Nova Araçá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4077, 21, 'Nova Bassano');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4078, 21, 'Nova Boa Vista');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4079, 21, 'Nova Bréscia');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4080, 21, 'Nova Candelária');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4081, 21, 'Nova Esperança do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4082, 21, 'Nova Hartz');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4083, 21, 'Nova Pádua');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4084, 21, 'Nova Palma');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4085, 21, 'Nova Petrópolis');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4086, 21, 'Nova Prata');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4087, 21, 'Nova Ramada');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4088, 21, 'Nova Roma do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4089, 21, 'Nova Santa Rita');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4090, 21, 'Novo Barreiro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4091, 21, 'Novo Cabrais');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4092, 21, 'Novo Hamburgo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4093, 21, 'Novo Machado');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4094, 21, 'Novo Tiradentes');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4095, 21, 'Osório');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4096, 21, 'Paim Filho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4097, 21, 'Palmares do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4098, 21, 'Palmeira das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4099, 21, 'Palmitinho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4100, 21, 'Panambi');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4101, 21, 'Pantano Grande');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4102, 21, 'Paraí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4103, 21, 'Paraíso do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4104, 21, 'Pareci Novo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4105, 21, 'Parobé');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4106, 21, 'Passa Sete');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4107, 21, 'Passo do Sobrado');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4108, 21, 'Passo Fundo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4109, 21, 'Paverama');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4110, 21, 'Pedro Osório');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4111, 21, 'Pejuçara');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4112, 21, 'Pelotas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4113, 21, 'Picada Café');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4114, 21, 'Pinhal');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4115, 21, 'Pinhal Grande');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4116, 21, 'Pinheirinho do Vale');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4117, 21, 'Pinheiro Machado');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4118, 21, 'Pirapó');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4119, 21, 'Piratini');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4120, 21, 'Planalto');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4121, 21, 'Poço das Antas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4122, 21, 'Pontão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4123, 21, 'Ponte Preta');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4124, 21, 'Portão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4125, 21, 'Porto Alegre');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4126, 21, 'Porto Lucena');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4127, 21, 'Porto Mauá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4128, 21, 'Porto Vera Cruz');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4129, 21, 'Porto Xavier');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4130, 21, 'Pouso Novo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4131, 21, 'Presidente Lucena');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4132, 21, 'Progresso');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4133, 21, 'Protásio Alves');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4134, 21, 'Putinga');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4135, 21, 'Quaraí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4136, 21, 'Quevedos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4137, 21, 'Quinze de Novembro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4138, 21, 'Redentora');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4139, 21, 'Relvado');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4140, 21, 'Restinga Seca');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4141, 21, 'Rio dos Índios');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4142, 21, 'Rio Grande');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4143, 21, 'Rio Pardo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4144, 21, 'Riozinho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4145, 21, 'Roca Sales');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4146, 21, 'Rodeio Bonito');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4147, 21, 'Rolante');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4148, 21, 'Ronda Alta');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4149, 21, 'Rondinha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4150, 21, 'Roque Gonzales');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4151, 21, 'Rosário do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4152, 21, 'Sagrada Família');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4153, 21, 'Saldanha Marinho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4154, 21, 'Salto do Jacuí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4155, 21, 'Salvador das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4156, 21, 'Salvador do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4157, 21, 'Sananduva');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4158, 21, 'Santa Bárbara do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4159, 21, 'Santa Clara do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4160, 21, 'Santa Cruz do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4161, 21, 'Santa Maria');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4162, 21, 'Santa Maria do Herval');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4163, 21, 'Santa Rosa');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4164, 21, 'Santa Tereza');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4165, 21, 'Santa Vitória do Palmar');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4166, 21, 'Santana da Boa Vista');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4167, 21, 'Santana do Livramento');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4168, 21, 'Santiago');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4169, 21, 'Santo Ângelo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4170, 21, 'Santo Antônio da Patrulha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4171, 21, 'Santo Antônio das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4172, 21, 'Santo Antônio do Palma');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4173, 21, 'Santo Antônio do Planalto');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4174, 21, 'Santo Augusto');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4175, 21, 'Santo Cristo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4176, 21, 'Santo Expedito do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4177, 21, 'São Borja');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4178, 21, 'São Domingos do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4179, 21, 'São Francisco de Assis');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4180, 21, 'São Francisco de Paula');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4181, 21, 'São Gabriel');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4182, 21, 'São Jerônimo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4183, 21, 'São João da Urtiga');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4184, 21, 'São João do Polêsine');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4185, 21, 'São Jorge');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4186, 21, 'São José das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4187, 21, 'São José do Herval');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4188, 21, 'São José do Hortêncio');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4189, 21, 'São José do Inhacorá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4190, 21, 'São José do Norte');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4191, 21, 'São José do Ouro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4192, 21, 'São José dos Ausentes');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4193, 21, 'São Leopoldo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4194, 21, 'São Lourenço do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4195, 21, 'São Luiz Gonzaga');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4196, 21, 'São Marcos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4197, 21, 'São Martinho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4198, 21, 'São Martinho da Serra');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4199, 21, 'São Miguel das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4200, 21, 'São Nicolau');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4201, 21, 'São Paulo das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4202, 21, 'São Pedro da Serra');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4203, 21, 'São Pedro do Butiá');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4204, 21, 'São Pedro do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4205, 21, 'São Sebastião do Caí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4206, 21, 'São Sepé');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4207, 21, 'São Valentim');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4208, 21, 'São Valentim do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4209, 21, 'São Valério do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4210, 21, 'São Vendelino');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4211, 21, 'São Vicente do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4212, 21, 'Sapiranga');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4213, 21, 'Sapucaia do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4214, 21, 'Sarandi');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4215, 21, 'Seberi');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4216, 21, 'Sede Nova');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4217, 21, 'Segredo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4218, 21, 'Selbach');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4219, 21, 'Senador Salgado Filho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4220, 21, 'Sentinela do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4221, 21, 'Serafina Corrêa');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4222, 21, 'Sério');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4223, 21, 'Sertão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4224, 21, 'Sertão Santana');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4225, 21, 'Sete de Setembro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4226, 21, 'Severiano de Almeida');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4227, 21, 'Silveira Martins');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4228, 21, 'Sinimbu');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4229, 21, 'Sobradinho');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4230, 21, 'Soledade');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4231, 21, 'Tabaí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4232, 21, 'Tapejara');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4233, 21, 'Tapera');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4234, 21, 'Tapes');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4235, 21, 'Taquara');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4236, 21, 'Taquari');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4237, 21, 'Taquaruçu do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4238, 21, 'Tavares');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4239, 21, 'Tenente Portela');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4240, 21, 'Terra de Areia');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4241, 21, 'Teutônia');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4242, 21, 'Tiradentes do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4243, 21, 'Toropi');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4244, 21, 'Torres');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4245, 21, 'Tramandaí');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4246, 21, 'Travesseiro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4247, 21, 'Três Arroios');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4248, 21, 'Três Cachoeiras');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4249, 21, 'Três Coroas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4250, 21, 'Três de Maio');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4251, 21, 'Três Forquilhas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4252, 21, 'Três Palmeiras');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4253, 21, 'Três Passos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4254, 21, 'Trindade do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4255, 21, 'Triunfo');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4256, 21, 'Tucunduva');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4257, 21, 'Tunas');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4258, 21, 'Tupanci do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4259, 21, 'Tupanciretã');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4260, 21, 'Tupandi');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4261, 21, 'Tuparendi');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4262, 21, 'Turuçu');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4263, 21, 'Ubiretama');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4264, 21, 'União da Serra');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4265, 21, 'Unistalda');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4266, 21, 'Uruguaiana');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4267, 21, 'Vacaria');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4268, 21, 'Vale do Sol');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4269, 21, 'Vale Real');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4270, 21, 'Vale Verde');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4271, 21, 'Vanini');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4272, 21, 'Venâncio Aires');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4273, 21, 'Vera Cruz');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4274, 21, 'Veranópolis');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4275, 21, 'Vespasiano Correa');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4276, 21, 'Viadutos');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4277, 21, 'Viamão');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4278, 21, 'Vicente Dutra');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4279, 21, 'Victor Graeff');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4280, 21, 'Vila Flores');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4281, 21, 'Vila Lângaro');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4282, 21, 'Vila Maria');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4283, 21, 'Vila Nova do Sul');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4284, 21, 'Vista Alegre');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4285, 21, 'Vista Alegre do Prata');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4286, 21, 'Vista Gaúcha');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4287, 21, 'Vitória das Missões');
INSERT INTO cidade (codigo, codigo_estado, nome) VALUES (4288, 21, 'Xangri-lá');

-- -----------------------------------------------------
-- Table usuario
-- -----------------------------------------------------
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Andres Sobieski', 'asobieski0@blogtalkradio.com', 'Goldenrod');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Ursala Leifer', 'uleifer1@bigcartel.com', 'Orange');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Seana Borland', 'sborland2@sphinn.com', 'Orange');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Reeta Edworthye', 'redworthye3@google.es', 'Maroon');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Dalton Lewry', 'dlewry4@vkontakte.ru', 'Red');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Hunt Loder', 'hloder5@goo.gl', 'Pink');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Chelsea Nayer', 'cnayer6@scientificamerican.com', 'Maroon');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Vernon Grimsdyke', 'vgrimsdyke7@addthis.com', 'Yellow');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Marsha Conybear', 'mconybear8@bloglines.com', 'Mauv');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Cletus Gaythwaite', 'cgaythwaite9@tuttocitta.it', 'Maroon');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Darb Czapla', 'dczaplaa@telegraph.co.uk', 'Green');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Fabian Scoggans', 'fscoggansb@cbc.ca', 'Yellow');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Siegfried Heiton', 'sheitonc@quantcast.com', 'Pink');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Marlow Comello', 'mcomellod@soup.io', 'Indigo');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Hilton Pegler', 'hpeglere@theguardian.com', 'Fuscia');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Stafani Blincowe', 'sblincowef@nps.gov', 'Blue');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Karia Barnard', 'kbarnardg@over-blog.com', 'Blue');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Elle Sandeford', 'esandefordh@goodreads.com', 'Indigo');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Cornelia Dailly', 'cdaillyi@nasa.gov', 'Purple');
insert into usuario (codigo, nome, email, senha) values (DEFAULT, 'Andi Pee', 'apeej@si.edu', 'Goldenrod');

-- -----------------------------------------------------
-- Table categoria
-- -----------------------------------------------------
insert into categoria (codigo, descricao) values (DEFAULT, 'Camisetas');
insert into categoria (codigo, descricao) values (DEFAULT, 'Camisas');
insert into categoria (codigo, descricao) values (DEFAULT, 'Casacos e Jaquetas');
insert into categoria (codigo, descricao) values (DEFAULT, 'Malha e Suéter');
insert into categoria (codigo, descricao) values (DEFAULT, 'Moletom');
insert into categoria (codigo, descricao) values (DEFAULT, 'Vestido');
insert into categoria (codigo, descricao) values (DEFAULT, 'Calça Social');
insert into categoria (codigo, descricao) values (DEFAULT, 'Calça Jeans');
insert into categoria (codigo, descricao) values (DEFAULT, 'Calça Esportiva');
insert into categoria (codigo, descricao) values (DEFAULT, 'Camiseta Esportiva');
insert into categoria (codigo, descricao) values (DEFAULT, 'Camisa Esportiva');

-- -----------------------------------------------------
-- Table tamanho
-- -----------------------------------------------------
insert into tamanho (codigo, tamanho) values (DEFAULT, 'PP');
insert into tamanho (codigo, tamanho) values (DEFAULT, 'P');
insert into tamanho (codigo, tamanho) values (DEFAULT, 'M');
insert into tamanho (codigo, tamanho) values (DEFAULT, 'G');
insert into tamanho (codigo, tamanho) values (DEFAULT, 'GG');
insert into tamanho (codigo, tamanho) values (DEFAULT, '36');
insert into tamanho (codigo, tamanho) values (DEFAULT, '38');
insert into tamanho (codigo, tamanho) values (DEFAULT, '40');
insert into tamanho (codigo, tamanho) values (DEFAULT, '42');
insert into tamanho (codigo, tamanho) values (DEFAULT, '44');
insert into tamanho (codigo, tamanho) values (DEFAULT, '46');
insert into tamanho (codigo, tamanho) values (DEFAULT, '48');
insert into tamanho (codigo, tamanho) values (DEFAULT, '50');

-- -----------------------------------------------------
-- Table produto
-- -----------------------------------------------------
insert into produto (codigo, referencia, descricao, preco, genero, codigo_categoria) values (DEFAULT, 10, 'Produto teste', '35.50', 'Unisex', 3);

-- -----------------------------------------------------
-- Table endereco
-- -----------------------------------------------------